---
- name: Set Time Zone to Africa/Johannesburg
  hosts: windows
  tasks:
    - name: Set time zone
      community.windows.win_timezone:
        timezone: "South Africa Standard Time"

    - name: Configure NTP settings
      win_shell: |
        w32tm /config /manualpeerlist:"time.windows.com,0x1" /syncfromflags:manual /reliable:YES /update
        w32tm /resync

    - name: Ensure NTP service is running
      win_service:
        name: W32Time
        start_mode: auto
        state: started
